
package lt.lba.xmlns.unifi.services.paymentsinitiation.v01;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.0
 * Sat Nov 27 13:30:48 EET 2010
 * Generated source version: 2.3.0
 * 
 */

@WebFault(name = "ServiceTemporarilyUnavailableFault", targetNamespace = "urn:lt:lba:xmlns:unifi:services:foundation:faults:V01")
public class ServiceIsTemporallyUnavailableFault extends Exception {
    public static final long serialVersionUID = 20101127133048L;
    
    private lt.lba.xmlns.unifi.services.foundation.faults.v01.TransportFaultType serviceTemporarilyUnavailableFault;

    public ServiceIsTemporallyUnavailableFault() {
        super();
    }
    
    public ServiceIsTemporallyUnavailableFault(String message) {
        super(message);
    }
    
    public ServiceIsTemporallyUnavailableFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceIsTemporallyUnavailableFault(String message, lt.lba.xmlns.unifi.services.foundation.faults.v01.TransportFaultType serviceTemporarilyUnavailableFault) {
        super(message);
        this.serviceTemporarilyUnavailableFault = serviceTemporarilyUnavailableFault;
    }

    public ServiceIsTemporallyUnavailableFault(String message, lt.lba.xmlns.unifi.services.foundation.faults.v01.TransportFaultType serviceTemporarilyUnavailableFault, Throwable cause) {
        super(message, cause);
        this.serviceTemporarilyUnavailableFault = serviceTemporarilyUnavailableFault;
    }

    public lt.lba.xmlns.unifi.services.foundation.faults.v01.TransportFaultType getFaultInfo() {
        return this.serviceTemporarilyUnavailableFault;
    }
}
