
package lt.lba.xmlns.unifi.services.paymentsinitiation.v01;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.0
 * Sat Nov 27 13:30:49 EET 2010
 * Generated source version: 2.3.0
 * 
 */

@WebFault(name = "SecurityAssertionFailedFault", targetNamespace = "urn:lt:lba:xmlns:unifi:services:foundation:faults:V01")
public class SecurityAssertionFailedFault extends Exception {
    public static final long serialVersionUID = 20101127133049L;
    
    private lt.lba.xmlns.unifi.services.foundation.faults.v01.TransportFaultType securityAssertionFailedFault;

    public SecurityAssertionFailedFault() {
        super();
    }
    
    public SecurityAssertionFailedFault(String message) {
        super(message);
    }
    
    public SecurityAssertionFailedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public SecurityAssertionFailedFault(String message, lt.lba.xmlns.unifi.services.foundation.faults.v01.TransportFaultType securityAssertionFailedFault) {
        super(message);
        this.securityAssertionFailedFault = securityAssertionFailedFault;
    }

    public SecurityAssertionFailedFault(String message, lt.lba.xmlns.unifi.services.foundation.faults.v01.TransportFaultType securityAssertionFailedFault, Throwable cause) {
        super(message, cause);
        this.securityAssertionFailedFault = securityAssertionFailedFault;
    }

    public lt.lba.xmlns.unifi.services.foundation.faults.v01.TransportFaultType getFaultInfo() {
        return this.securityAssertionFailedFault;
    }
}
