<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions name="PaymentsInitiationV01"
	targetNamespace="urn:lt:lba:xmlns:unifi:services:PaymentsInitiation:V01"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:lt:lba:xmlns:unifi:services:PaymentsInitiation:V01"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsam="http://www.w3.org/2007/02/addressing/metadata">
	<wsdl:documentation>Version: 1.0.3</wsdl:documentation>

	<wsp:Policy wsu:Id="SignAndEncrypt"
		xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
		xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
		wsdl:required="true">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:AsymmetricBinding>
					<wsp:Policy>
						<sp:InitiatorToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
									<wsp:Policy>
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:InitiatorToken>
						<sp:RecipientToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
									<wsp:Policy>
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:RecipientToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256Rsa15 />
								<sp:TripleDesRsa15 />
								<sp:Basic128Rsa15 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:IncludeTimestamp />
						<sp:EncryptSignature />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:AsymmetricBinding>
				<sp:Wss10>
					<wsp:Policy>
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefEmbeddedToken />
					</wsp:Policy>
				</sp:Wss10>
				<sp:Layout>
					<wsp:Policy>
						<sp:Lax />
					</wsp:Policy>
				</sp:Layout>
				<sp:SignedParts>
					<sp:Body />
					<sp:Header Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Namespace="http://www.w3.org/2005/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts>
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="Addressing"
		xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
		xmlns:wsp="http://www.w3.org/ns/ws-policy"
		wsdl:required="true">
		<wsam:Addressing>
			<wsp:Policy>
				<wsam:NonAnonymousResponses />
			</wsp:Policy>
		</wsam:Addressing>
	</wsp:Policy>
	
	<wsp:Policy wsu:Id="AddressingAnonymous"
		xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
		xmlns:wsp="http://www.w3.org/ns/ws-policy"
		wsdl:required="true">
		<wsam:Addressing>
			<wsp:Policy />
		</wsam:Addressing>
	</wsp:Policy>	
</wsdl:definitions>
