package lt.lba.xmlns.unifi.services.paymentsinitiation.v01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.3.0
 * Sat Nov 27 13:30:49 EET 2010
 * Generated source version: 2.3.0
 * 
 */
 
@WebService(targetNamespace = "urn:lt:lba:xmlns:unifi:services:PaymentsInitiation:V01", name = "PaymentsInitiationV01")
@XmlSeeAlso({lt.lba.xmlns.unifi.services.foundation.faults.v01.ObjectFactory.class, lt.lba.xmlns._2011._11.unifi.customercredittransferinitiation.v03.ObjectFactory.class, iso.std.iso._20022.tech.xsd.pain_001_001.ObjectFactory.class, iso.std.iso._20022.tech.xsd.pain_007_001.ObjectFactory.class, lt.lba.xmlns._2011._11.unifi.customerdirectdebitinitiation.v02.ObjectFactory.class, iso.std.iso._20022.tech.xsd.pain_002_001.ObjectFactory.class, lt.lba.xmlns._2011._11.unifi.customerpaymentreversal.v02.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class, iso.std.iso._20022.tech.xsd.pain_008_001.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PaymentsInitiationV01 {

    @Action(input = "urn:lt:lba:xmlns:unifi:services:PaymentsInitiation:V01/PaymentsInitiationV01/CustomerDirectDebitInitiationV02/CustomerDirectDebitInitiationV02Request", fault = {})
    @WebResult(name = "Document", targetNamespace = "urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", partName = "document")
    @WebMethod(operationName = "CustomerDirectDebitInitiationV02", action = "urn:lt:lba:xmlns:unifi:services:PaymentsInitiation:V01/CustomerDirectDebitInitiationV02")
    public iso.std.iso._20022.tech.xsd.pain_002_001.Document customerDirectDebitInitiationV02(
        @WebParam(partName = "document", name = "SignableDocument", targetNamespace = "http://www.lba.lt/xmlns/2011/11/unifi/CustomerDirectDebitInitiation/V02")
        lt.lba.xmlns._2011._11.unifi.customerdirectdebitinitiation.v02.SignableDocumentType document
    ) throws ServiceIsTemporallyUnavailableFault, SecurityAssertionFailedFault;

    @Action(input = "urn:lt:lba:xmlns:unifi:services:PaymentsInitiation:V01/PaymentsInitiationV01/CustomerPaymentReversalV02/CustomerPaymentReversalV02Request", fault = {})
    @WebResult(name = "Document", targetNamespace = "urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", partName = "document")
    @WebMethod(operationName = "CustomerPaymentReversalV02", action = "urn:lt:lba:xmlns:unifi:services:PaymentsInitiation:V01/CustomerPaymentReversalV02")
    public iso.std.iso._20022.tech.xsd.pain_002_001.Document customerPaymentReversalV02(
        @WebParam(partName = "document", name = "SignableDocument", targetNamespace = "http://www.lba.lt/xmlns/2011/11/unifi/CustomerPaymentReversal/V02")
        lt.lba.xmlns._2011._11.unifi.customerpaymentreversal.v02.SignableDocumentType document
    ) throws ServiceIsTemporallyUnavailableFault, SecurityAssertionFailedFault;

    @Action(input = "urn:lt:lba:xmlns:unifi:services:PaymentsInitiation:V01/PaymentsInitiationV01/CustomerCreditTransferInitiationV03/CustomerCreditTransferInitiationV03Request", fault = {})
    @WebResult(name = "Document", targetNamespace = "urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", partName = "document")
    @WebMethod(operationName = "CustomerCreditTransferInitiationV03", action = "urn:lt:lba:xmlns:unifi:services:PaymentsInitiation:V01/CustomerCreditTransferInitiationV03")
    public iso.std.iso._20022.tech.xsd.pain_002_001.Document customerCreditTransferInitiationV03(
        @WebParam(partName = "document", name = "SignableDocument", targetNamespace = "http://www.lba.lt/xmlns/2011/11/unifi/CustomerCreditTransferInitiation/V03")
        lt.lba.xmlns._2011._11.unifi.customercredittransferinitiation.v03.SignableDocumentType document
    ) throws ServiceIsTemporallyUnavailableFault, SecurityAssertionFailedFault;
}
